name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or whichever branch you use for development

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install wasm-pack
        run: cargo install wasm-pack

      - name: Build Wasm package
        run: wasm-pack build --target web --release

      - name: Prepare deploy directory
        run: |
          mkdir -p dist
          cp index.html dist/
          cp -r pkg dist/pkg

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
